---
- name: Service account | generate file
  ansible.builtin.include_tasks: _cfg_template.yml
  vars:
    _cfg_template_dest_file: etc/irods/service_account.config

- name: Service account | ensure known that changes were made
  ansible.builtin.meta: flush_handlers
