---
- name: Setup iRODS | Initialize ICAT schema if needed
  when: irods_cfg_catalog_service_role == 'provider'
  block:
    - name: Determine if ICAT schema initialized
      ansible.builtin.stat:
        path: "{{ _root_dir }}/var/lib/irods/.odbc.ini"
      register: odbc

    - name: Load variable values
      when: not odbc.stat.exists
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - server_config.yml
        - irods_environment_server.yml

    - name: Create setup configuration file
      when: not odbc.stat.exists
      ansible.builtin.template:
        src: setup_configuration.json.j2
        dest: /tmp/setup_configuration.json
        mode: u+rw

    - name: Initialize ICAT schema
      when: not odbc.stat.exists
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -o errexit
          python3 /var/lib/irods/scripts/setup_irods.py --stdout --test --verbose \
            --json_configuration_file=/tmp/setup_configuration.json
          rm --force /var/lib/irods/log/test_mode_output.log /tmp/setup_configuration.json || true
      register: response
      changed_when: response.stdout is search('Updating to schema version')
  rescue:
    - name: Ensure .odbc.ini missing on failure
      ansible.builtin.file:
        path: "{{ _root_dir }}/var/lib/irods/.odbc.ini"
        state: absent

    - name: Fail
      ansible.builtin.fail:

- name: Setup iRODS | configure server
  ansible.builtin.import_tasks: server.yml
