---
- name: Determine if already initialized
  ansible.builtin.stat:
    path: "{{ _root_dir }}/var/lib/irods/version.json"
  register: version

- name: Setup iRODS | Initialize ICAT schema if needed
  when: not version.stat.exists
  block:
    - name: Load variable values
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - server_config.yml
        - irods_environment_server.yml

    - name: Create setup configuration file
      ansible.builtin.template:
        src: setup_configuration.json.j2
        dest: /tmp/setup_configuration.json
        mode: u+rw

    - name: Setup iRODS
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -o errexit
          python3 /var/lib/irods/scripts/setup_irods.py --stdout --test --verbose \
            --json_configuration_file=/tmp/setup_configuration.json
          rm --force /var/lib/irods/log/test_mode_output.log /tmp/setup_configuration.json || true
      register: resp
      changed_when: resp.stdout is search('Updating /var/lib/irods/version.json')

  rescue:
    - name: Ensure version is missing on failure
      ansible.builtin.file:
        path: "{{ _root_dir }}/var/lib/irods/version.json"
        state: absent

    - name: Fail
      ansible.builtin.fail:

- name: Setup iRODS | configure server
  ansible.builtin.import_tasks: server.yml
