---
- name: Provision
  ansible.builtin.import_playbook: irods_provision.yml


- name: Ensure catalog service providers are started
  hosts: irods_catalog
  become: "{{ _irods_become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: Start iRODS
      cyverse.ds.irods_ctl:


- name: Create clerver user
  hosts: irods_resource:!irods_catalog
  vars:
    admin_user: "{{ hostvars[groups['irods_catalog'][0]]['_irods_clerver_user'] }}"
    admin_password: "{{ hostvars[groups['irods_catalog'][0]]['_irods_clerver_password'] }}"
  tasks:
    - name: Create clerver user
      delegate_to: localhost
      cyverse.ds.irods_user:
        name: "{{ _irods_clerver_user }}"
        type: rodsadmin
        state: present
        password: "{{ _irods_clerver_password }}"
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ admin_user }}"
        admin_password: "{{ admin_password }}"
        zone: "{{ _irods_zone_name }}"

    - name: Ensure clerver user is in group rodsadmin
      delegate_to: localhost
      cyverse.ds.irods_group_member:
        group: rodsadmin
        users:
          - "{{ _irods_clerver_user }}"
        state: present
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ admin_user }}"
        admin_password: "{{ admin_password }}"
        zone: "{{ _irods_zone_name }}"


- name: Correctly configure iRODS
  ansible.builtin.import_playbook: irods_cfg.yml


- name: Bootstrap iRODS start
  hosts: irods_resource:!irods_catalog
  become: "{{ _irods_become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  become_flags: '-i'
  tasks:
    - name: Start iRODS
      cyverse.ds.irods_ctl:


- name: Create storage resources
  ansible.builtin.import_playbook: irods_storage_resources.yml
