---
# These are the config file specific defaults for the server side
# irods_environment.json

_client_default_hash_scheme_default: "{{ irods_cfg_default_hash_scheme }}"
_client_default_resource_default: "{{ irods_cfg_default_resource_name }}"
_client_encryption_algorithm_default: "{{ irods_cfg_server_control_plane_encryption_algorithm }}"
_client_encryption_key_size_default: 32
_client_encryption_num_hash_rounds_default: >-
  {{ irods_cfg_server_control_plane_encryption_num_hash_rounds }}
_client_encryption_salt_size_default: 8
_client_server_negotiation_default: request_server_negotiation
_client_server_policy_default: CS_NEG_REFUSE

_connection_pool_refresh_time_default: 300

_cwd_default: "{{ irods_cfg_home }}"

_default_number_of_transfer_threads_default: 4

_environment_file_default: var/lib/irods/.irods/irods_environment.json

_for_server_default: true

_home_default: /{{ irods_cfg_zone_name }}/home/{{ irods_cfg_zone_user }}

_match_hash_policy_default: compatible

_maximum_size_for_single_buffer_default: 32

_transfer_buffer_size_for_parallel_transfer_default: 4

_server_control_plane_encryption_algorithm_default: AES-256-CBC
_server_control_plane_encryption_num_hash_rounds_default: 16
_server_control_plane_key_default: 32_byte_server_control_plane_key
_server_control_plane_port_default: 1248
